apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: auto-raise-hpa
build:
  artifacts:
  - image: asia.gcr.io/pl-web-219210/auto-raise-hpa
    kaniko: {}
  googleCloudBuild:
    projectId: pl-web-219210
deploy:
  kustomize:
    paths:
    - kustomize
